# Server port
server.port=8080

spring.datasource.username=root
spring.datasource.password=nANI@123
spring.datasource.url=jdbc:mysql://localhost:3306/studentportal
spring.jpa.hibernate.ddl-auto=update


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true


